#!/usr/bin/env python3
# pyright: strict
"""Embed the Unicode 15.0.0 tables tool_search matches with in both implementations.

    python3 spec/tools/gen_unicode_fold.py           # rewrite the generated modules
    python3 spec/tools/gen_unicode_fold.py --check   # exit 1 if either is stale

Stdlib only, Python 3.12+. Reads spec/unicode/15.0.0 (CaseFolding.txt, DerivedGeneralCategory.txt,
PropList.txt) through fixtures/ucd.py, the same reader the conformance generator uses, and writes
one table per language: the assigned code points, the L/M/N classes, the query separators and the
full case folding (status C and F). Both runtimes then match byte for byte whatever Unicode
version they ship (spec/schema/README.md, "tool_search").
"""

import sys
from pathlib import Path

from fixtures.ucd import VERSION, tables

ROOT = Path(__file__).resolve().parents[2]
PYTHON = ROOT / "python" / "src" / "threads" / "_generated" / "fold_table.py"
TYPESCRIPT = (
    ROOT / "typescript" / "packages" / "core" / "src" / "tools" / "generated" / "fold-table.ts"
)
HEADER = "Generated by spec/tools/gen_unicode_fold.py from spec/unicode/15.0.0. Do not edit."


def _ranges(spans: tuple[tuple[int, int], ...]) -> str:
    return ",".join(f"{lo:x}-{hi:x}" for lo, hi in spans)


def _data() -> dict[str, str]:
    t = tables()
    return {
        "ASSIGNED": _ranges(t.assigned),
        "WORD": _ranges(t.word),
        "SEPARATORS": ",".join(f"{c:x}" for c in sorted(t.separators)),
        "FOLD": ",".join(
            f"{k:x}:{' '.join(f'{c:x}' for c in v)}" for k, v in sorted(t.fold.items())
        ),
    }


def python() -> str:
    d = _data()
    return (
        f"# {HEADER}\n"
        '"""The Unicode tables tool_search matches with, parsed once at import."""\n\n'
        "from collections.abc import Mapping\n"
        "from typing import Final\n\n"
        f'UNICODE_VERSION: Final = "{VERSION}"\n'
        f'_ASSIGNED: Final = "{d["ASSIGNED"]}"  # noqa: E501\n'
        f'_WORD: Final = "{d["WORD"]}"  # noqa: E501\n'
        f'_SEPARATORS: Final = "{d["SEPARATORS"]}"  # noqa: E501\n'
        f'_FOLD: Final = "{d["FOLD"]}"  # noqa: E501\n\n\n'
        "def _ranges(text: str) -> tuple[tuple[int, int], ...]:\n"
        "    return tuple((int(lo, 16), int(hi, 16)) "
        'for lo, hi in (r.split("-") for r in text.split(",")))\n\n\n'
        "ASSIGNED: Final = _ranges(_ASSIGNED)\n"
        '"""Inclusive ranges of the code points assigned in Unicode 15.0.0, but surrogates."""\n'
        "WORD: Final = _ranges(_WORD)\n"
        '"""Inclusive ranges of General_Category L*, M* and N*."""\n'
        'SEPARATORS: Final = frozenset(int(c, 16) for c in _SEPARATORS.split(","))\n'
        '"""`,`, every White_Space code point, U+001C-U+001F and U+FEFF."""\n'
        "FOLD: Final[Mapping[int, str]] = {\n"
        '    int(k, 16): "".join(chr(int(c, 16)) for c in v.split())\n'
        '    for k, v in (e.split(":") for e in _FOLD.split(","))\n'
        "}\n"
        '"""Full case folding: CaseFolding.txt status C and F."""\n'
    )


def typescript() -> str:
    d = _data()
    return (
        f"// {HEADER}\n\n"
        "const ranges = (text: string): readonly (readonly [number, number])[] =>\n"
        '  text.split(",").map((r) => {\n'
        '    const [lo = "", hi = ""] = r.split("-");\n'
        "    return [Number.parseInt(lo, 16), Number.parseInt(hi, 16)] as const;\n"
        "  });\n\n"
        f'export const UNICODE_VERSION: string = "{VERSION}";\n\n'
        "/** Inclusive ranges of the code points assigned in Unicode 15.0.0, but surrogates. */\n"
        "export const ASSIGNED: readonly (readonly [number, number])[] = ranges(\n"
        f'  "{d["ASSIGNED"]}",\n);\n\n'
        "/** Inclusive ranges of General_Category L*, M* and N*. */\n"
        "export const WORD: readonly (readonly [number, number])[] = ranges(\n"
        f'  "{d["WORD"]}",\n);\n\n'
        "/** `,`, every White_Space code point, U+001C-U+001F and U+FEFF. */\n"
        "export const SEPARATORS: ReadonlySet<number> = new Set(\n"
        f'  "{d["SEPARATORS"]}".split(",").map((c) => Number.parseInt(c, 16)),\n);\n\n'
        "/** Full case folding: CaseFolding.txt status C and F. */\n"
        "export const FOLD: ReadonlyMap<number, string> = new Map(\n"
        f'  "{d["FOLD"]}".split(",").map((e) => {{\n'
        '    const [k = "", v = ""] = e.split(":");\n'
        "    return [\n"
        "      Number.parseInt(k, 16),\n"
        '      String.fromCodePoint(...v.split(" ").map((c) => Number.parseInt(c, 16))),\n'
        "    ] as const;\n"
        "  }),\n);\n"
    )


def main(argv: list[str]) -> int:
    check = argv == ["--check"]
    if argv and not check:
        print(__doc__)
        return 2
    stale = 0
    for path, text in ((PYTHON, python()), (TYPESCRIPT, typescript())):
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == text:
            continue
        if check:
            print(f"{path.relative_to(ROOT)} is stale: run spec/tools/gen_unicode_fold.py")
            stale = 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    return stale


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
