#!/usr/bin/env python3
# pyright: strict
"""Generate the factory signature checks from spec/api.json (lane 15).

    python3 spec/tools/gen_api_surface_factories.py            # write every generated file
    python3 spec/tools/gen_api_surface_factories.py --api A --ts-package P --ts-out F

Stdlib only; the output is not committed (scripts/generate.sh writes it). For each adapter
package, TypeScript gets `typescript/packages/<dir>/test/generated/factories.ts`, compiled by that
package's `tsc -p`: positional arity and each positional type, the exact option key set, each
option's required flag and exact type (callbacks and platform types included), and that the
return type is assignable to the declared protocol. Python gets
`python/tests/spec_tools/generated/factories.py`, checked by pyright strict: each factory called
with its declared positional types and required options returns the declared protocol. The rest
of the Python proof (arity, kinds, exact annotations, keyword-only defaults) is
`factory_surface_py.py` at test time.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import TYPE_CHECKING

from factory_surface_py import modules_of
from typeexpr_render import Obj, Render, camel, obj, objs, text

if TYPE_CHECKING:
    from typeexpr_render import Json

ROOT = pathlib.Path(__file__).resolve().parents[2]
API = ROOT / "spec" / "api.json"
PY_OUT = ROOT / "python" / "tests" / "spec_tools" / "generated" / "factories.py"
HEADER = "Generated by spec/tools/gen_api_surface_factories.py from spec/api.json. Do not edit."
TS_HELPERS = [
    "type Equals<A, B> =",
    "  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;",
    "type Assert<T extends true> = T;",
    "type IsRequired<O, K extends keyof O> = {} extends Pick<O, K> ? false : true;",
]
IDENT = re.compile(r"^[A-Z]\w*$")


def factories(api: Obj, package: str) -> list[tuple[str, Obj]]:
    """The functions of one package, in contract order."""
    return [
        (k, obj(f))
        for k, f in obj(api["functions"]).items()
        if obj(f).get("package", "core") == package
    ]


def adapter_packages(api: Obj) -> list[str]:
    return [k for k, p in obj(api["packages"]).items() if obj(p).get("kind") == "adapter"]


def _params(f: Obj, lang: str, kind: str) -> list[Obj]:
    return [
        p
        for p in objs(f.get("params", []))
        if p.get("kind") == kind and p.get("lang", lang) == lang
    ]


def _walk(t: Json) -> list[Obj]:
    """Every object node inside a type expression (or a list of params)."""
    if isinstance(t, dict):
        return [t, *(n for v in t.values() for n in _walk(v))]
    if isinstance(t, list):
        return [n for v in t for n in _walk(v)]
    return []


def _refs(t: Json) -> set[str]:
    """Contract type names ($ref #/types/X) inside a type."""
    return {
        ref.removeprefix("#/types/")
        for n in _walk(t)
        if isinstance(ref := n.get("$ref"), str) and ref.startswith("#/types/")
    }


def _platforms(t: Json, lang: str) -> set[str]:
    """The platform type spellings for one language inside a type."""
    return {
        spelled
        for n in _walk(t)
        if isinstance(spelled := obj(n.get("platform", {})).get(lang), str)
    }


def _arity(positional: list[Obj], options: list[Obj]) -> str:
    """The allowed lengths of Parameters<F>: optional positionals, then an options object."""
    count = len(positional)
    least = sum(1 for p in positional if p.get("required"))
    lengths = list(range(least, count + 1))
    if any(p.get("required") for p in options):
        lengths = [count + 1]
    elif options:
        lengths.append(count + 1)
    return " | ".join(str(n) for n in lengths)


def _assert(name: str, check: str) -> str:
    return f"export type {name} = Assert<{check}>;"


def ts_lines(key: str, f: Obj) -> list[str]:
    r = Render("ts")
    fn = f"typeof pkg.{text(f['ts'])}"
    positional, options = _params(f, "ts", "positional"), _params(f, "ts", "option")
    arity = _arity(positional, options)
    out = [_assert(f"{key}_arity", f'Equals<Parameters<{fn}>["length"], {arity}>')]
    for i, p in enumerate(positional):
        want = r.expr(obj(p["type"]))
        out.append(
            _assert(f"{key}_{text(p['name'])}", f"Equals<Required<Parameters<{fn}>>[{i}], {want}>")
        )
    opts = f"NonNullable<Parameters<{fn}>[{len(positional)}]>"
    if options:  # with none, the arity check already refuses a trailing options object
        keys = " | ".join(json.dumps(camel(text(p["name"]))) for p in options)
        out.append(_assert(f"{key}_option_keys", f"Equals<keyof {opts}, {keys}>"))
    for p in options:
        at = f"{key}_{text(p['name'])}"
        name = json.dumps(camel(text(p["name"])))
        want, req = r.expr(obj(p["type"])), "true" if p.get("required") else "false"
        out.append(_assert(at, f"Equals<Required<{opts}>[{name}], {want}>"))
        out.append(_assert(f"{at}_required", f"Equals<IsRequired<{opts}, {name}>, {req}>"))
    ret = r.returns(f, bool(f.get("async")))
    out.append(_assert(f"{key}_returns", f"ReturnType<{fn}> extends {ret} ? true : false"))
    return out


def _used(f: Obj, lang: str) -> Json:
    """The params of one language and the return type: what the generated file names."""
    params: list[Json] = [p for p in objs(f.get("params", [])) if p.get("lang", lang) == lang]
    return [params, f.get("returns")]


def render_ts(api: Obj, packages: list[str]) -> str:
    """The checks for the factories of the packages one TS entry holds. Contract types come from
    the core package; a bare platform name (`WebTransport`) from the factory's own package."""
    pkg = text(obj(obj(api["packages"])[packages[0]])["ts"])
    core = text(obj(obj(api["packages"])["core"])["ts"])
    fns = [(k, f) for p in packages for k, f in factories(api, p) if f.get("lang", "ts") == "ts"]
    used = [_used(f, "ts") for _, f in fns]
    imports: dict[str, set[str]] = {core: set[str]().union(*(_refs(u) for u in used))}
    own = {n for u in used for n in _platforms(u, "ts") if IDENT.match(n)}
    imports.setdefault(pkg, set()).update(own)
    lines = [f"// {HEADER}"]
    lines += [
        f'import type {{ {", ".join(sorted(names))} }} from "{m}";'
        for m, names in imports.items()
        if names
    ]
    lines += [f'import type * as pkg from "{pkg}";', "", *TS_HELPERS, ""]
    for key, f in fns:
        lines += ts_lines(key, f)
    return "\n".join(lines) + "\n"


def _py_inputs(f: Obj) -> tuple[list[Obj], list[Obj]]:
    """The params the Python helper names: the positional ones and the required options."""
    required = [p for p in _params(f, "py", "option") if p.get("required")]
    return _params(f, "py", "positional"), required


def _py_helper(key: str, f: Obj, r: Render) -> list[str]:
    """A function taking the declared positional types and required options, calling the
    factory with them (options by name), and keeping the result as the declared protocol."""
    positional, required = _py_inputs(f)
    args = [f"{text(p['name'])}: {r.expr(obj(p['type']))}" for p in positional]
    if required:
        args += ["*", *(f"{text(p['name'])}: {r.expr(obj(p['type']))}" for p in required)]
    call = [text(p["name"]) for p in positional]
    call += [f"{text(p['name'])}={text(p['name'])}" for p in required]
    return [
        "",
        "",
        f"def returns_{key}({', '.join(args)}) -> None:",
        f"    returned: {r.returns(f, False)} = {text(f['py'])}({', '.join(call)})",
        "    del returned",
    ]


def render_py(api: Obj) -> str:
    """Each factory, called with its declared inputs, returns its declared protocol. Contract
    types come from `threads`; a qualified platform type (`httpx.AsyncBaseTransport`) imports
    its module (everything before the last dot)."""
    r = Render("py")
    names: dict[str, set[str]] = {}
    modules: set[str] = set()
    body: list[str] = []
    for package in adapter_packages(api):
        module = obj(obj(api["packages"])[package]).get("py")
        for key, f in factories(api, package):
            if not isinstance(module, str) or f.get("lang", "py") != "py":
                continue
            names.setdefault(module, set()).add(text(f["py"]))
            # Only what the helper spells: an import of an optional option's type is unused.
            named: Json = [*(p for ps in _py_inputs(f) for p in ps), f.get("returns")]
            names.setdefault("threads", set()).update(_refs(named))
            modules.update(m for t in _platforms(named, "py") for m in modules_of(t))
            body += _py_helper(key, f, r)
    lines = [f'"""{HEADER}"""', ""]
    lines += [f"import {m}" for m in sorted(modules)]
    lines += [f"from {m} import {', '.join(sorted(n))}" for m, n in sorted(names.items()) if n]
    return "\n".join([*lines, *body]) + "\n"


def ts_out(api: Obj, package: str) -> pathlib.Path:
    """typescript/packages/<dir>/test/generated/factories.ts for @threads/<dir>."""
    spec = text(obj(obj(api["packages"])[package])["ts"])
    return (
        ROOT
        / "typescript"
        / "packages"
        / spec.rpartition("/")[2]
        / "test"
        / "generated"
        / "factories.ts"
    )


def write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api", type=pathlib.Path, default=API)
    parser.add_argument("--ts-package", help="write only this package's TS checks, to --ts-out")
    parser.add_argument("--ts-out", type=pathlib.Path)
    args = parser.parse_args(argv)
    api_path: pathlib.Path = args.api
    api = obj(json.loads(api_path.read_text()))
    package: str | None = args.ts_package
    out: pathlib.Path | None = args.ts_out
    if package is not None and out is not None:
        write(out, render_ts(api, [package]))
        return 0
    by_file: dict[pathlib.Path, list[str]] = {}
    for p in adapter_packages(api):
        if "ts" in obj(obj(api["packages"])[p]):
            by_file.setdefault(ts_out(api, p), []).append(p)
    for path, packages in by_file.items():
        write(path, render_ts(api, packages))
    write(PY_OUT, render_py(api))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
