#!/usr/bin/env python3
# pyright: strict
"""Embed spec/schema/store.sql in both implementations.

    python3 spec/tools/gen_store_sql.py           # rewrite the embedded constants
    python3 spec/tools/gen_store_sql.py --check   # exit 1 if either is stale

Stdlib only, Python 3.12+. Each store runs the embedded DDL, never a file under spec/, so the
constant is generated here and CI fails when it drifts from store.sql. The Postgres DDL is
translated by store_pg.py, which refuses any construct it doesn't know.
"""

import re
import sys
from pathlib import Path

from store_pg import postgres

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "spec" / "schema" / "store.sql"
PYTHON = ROOT / "python" / "src" / "threads" / "_generated" / "store_sql.py"
TYPESCRIPT = ROOT / "typescript" / "packages" / "core" / "src" / "store" / "generated" / "sql.ts"
PYTHON_PG = ROOT / "python" / "src" / "threads" / "_generated" / "store_pg_sql.py"
TYPESCRIPT_PG = ROOT / "typescript" / "packages" / "postgres" / "src" / "generated" / "sql.ts"
HEADER = "Generated by spec/tools/gen_store_sql.py from spec/schema/store.sql. Do not edit."


def version(sql: str) -> int:
    found = re.findall(r"^PRAGMA user_version = (\d+);$", sql, flags=re.MULTILINE)
    if len(found) != 1:
        raise SystemExit("store.sql must set PRAGMA user_version exactly once")
    return int(found[0])


def python(sql: str, ddl: str, engine: str) -> str:
    if "\\" in ddl or '"""' in ddl:
        raise SystemExit("store.sql can't hold a backslash or triple quote")
    return (
        f"# {HEADER}\n"
        f'"""The normative log store DDL ({engine}) and its schema version."""\n\n'
        "from typing import Final\n\n"
        f'STORE_SQL: Final[str] = """\\\n{ddl}"""\n'
        f"STORE_VERSION: Final[int] = {version(sql)}\n"
    )


def typescript(sql: str, ddl: str, engine: str) -> str:
    escaped = ddl.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return (
        f"// {HEADER}\n\n"
        f"/** The normative log store DDL ({engine}). */\n"
        f"export const STORE_SQL: string = `{escaped}`;\n\n"
        "/** The schema version store.sql sets as PRAGMA user_version. */\n"
        f"export const STORE_VERSION: number = {version(sql)};\n"
    )


def main(argv: list[str]) -> int:
    check = argv == ["--check"]
    if argv and not check:
        print(__doc__)
        return 2
    sql = SOURCE.read_text(encoding="utf-8")
    pg = postgres(sql)
    stale = 0
    outputs = (
        (PYTHON, python(sql, sql, "SQLite")),
        (TYPESCRIPT, typescript(sql, sql, "SQLite")),
        (PYTHON_PG, python(sql, pg, "Postgres")),
        (TYPESCRIPT_PG, typescript(sql, pg, "Postgres")),
    )
    for path, text in outputs:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == text:
            continue
        if check:
            print(f"{path.relative_to(ROOT)} is stale: run spec/tools/gen_store_sql.py")
            stale = 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    return stale


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
