#!/usr/bin/env python3
# pyright: strict
"""Embed spec/schema/limits.json's numbers in both implementations.

    python3 spec/tools/gen_limits.py           # rewrite the generated modules
    python3 spec/tools/gen_limits.py --check   # exit 1 if either is stale

Stdlib only, Python 3.12+. A limit that decides what a run records (the bytes web_fetch keeps, so
its content hash) has to be one number in both languages: written in code it is two numbers that
happen to agree, and 5 MiB against 10 MiB is what this file exists to prevent. The source reads no
file under spec/ at run time, so the number is generated in.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "spec" / "schema" / "limits.json"
PYTHON = ROOT / "python" / "src" / "threads" / "_generated" / "limits.py"
TYPESCRIPT = ROOT / "typescript" / "packages" / "core" / "src" / "tools" / "generated" / "limits.ts"
HEADER = "Generated by spec/tools/gen_limits.py from spec/schema/limits.json. Do not edit."
DOC_CHARS = 90
"""A doc is one line of generated Python, and the line has to fit ruff's limit."""


type Json = str | int | float | bool | list[Json] | dict[str, Json] | None


def _obj(value: Json, at: str) -> dict[str, Json]:
    if not isinstance(value, dict):
        raise SystemExit(f"limits.json: {at} must be an object")
    return value


def limits() -> list[tuple[str, int, str]]:
    """(name, value, doc) per limit, in name order: the generated modules are stable byte for
    byte. A group holds its limits and the one `doc` they share."""
    source = _obj(json.loads(SOURCE.read_text(encoding="utf-8")), "the file")
    found: list[tuple[str, int, str]] = []
    for group in sorted(source):
        if group == "description":
            continue
        body = _obj(source[group], group)
        doc = body.get("doc")
        if not isinstance(doc, str) or len(doc) > DOC_CHARS:
            raise SystemExit(f"{group}.doc must be one line of at most {DOC_CHARS} characters")
        for limit in sorted(body):
            if limit == "doc":
                continue
            value = body[limit]
            if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
                raise SystemExit(f"{group}.{limit} must be a positive integer")
            found.append((f"{group}_{limit}".upper(), value, doc))
    if not found:
        raise SystemExit("limits.json declares no limit")
    return found


def python(found: list[tuple[str, int, str]]) -> str:
    body = "".join(f'{n}: Final[int] = {v}\n"""{d}"""\n' for n, v, d in found)
    return (
        f"# {HEADER}\n"
        '"""The limits spec/schema/limits.json fixes for both languages."""\n\n'
        "from typing import Final\n\n"
        f"{body}"
    )


def typescript(found: list[tuple[str, int, str]]) -> str:
    body = "\n".join(f"/** {d} */\nexport const {n}: number = {v};" for n, v, d in found)
    return f"// {HEADER}\n\n{body}\n"


def main(argv: list[str]) -> int:
    check = argv == ["--check"]
    if argv and not check:
        print(__doc__)
        return 2
    found = limits()
    stale = 0
    for path, text in ((PYTHON, python(found)), (TYPESCRIPT, typescript(found))):
        if (path.read_text(encoding="utf-8") if path.exists() else "") == text:
            continue
        if check:
            print(f"{path.relative_to(ROOT)} is stale: run spec/tools/gen_limits.py")
            stale = 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    return stale


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
