#!/usr/bin/env python3
# pyright: strict
"""Embed spec/models/<provider>.v1.json in both implementations (not committed; generate.sh).

    python3 spec/tools/gen_model_catalogs.py

Stdlib only. The factories read no file under spec/ at run time: each language parses these
exact bytes through its catalog schema when its model catalog module loads.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODELS = ROOT / "spec" / "models"
PYTHON = ROOT / "python" / "src" / "threads" / "_generated" / "model_catalogs.py"
TYPESCRIPT = (
    ROOT / "typescript" / "packages" / "core" / "src" / "model" / "generated" / "catalogs.ts"
)
HEADER = "Generated by spec/tools/gen_model_catalogs.py from spec/models/. Do not edit."


def catalogs() -> list[str]:
    return [p.read_text(encoding="utf-8") for p in sorted(MODELS.glob("*.v1.json"))]


def python(texts: list[str]) -> str:
    items = "".join(f"    {json.dumps(t)},\n" for t in texts)
    return (
        f"# {HEADER}\n"
        '"""Each provider\'s model catalog, as the bytes of its spec file."""\n\n'
        "from typing import Final\n\n"
        f"MODEL_CATALOGS: Final[tuple[str, ...]] = (\n{items})\n"
    )


def typescript(texts: list[str]) -> str:
    items = "".join(f"  {json.dumps(t)},\n" for t in texts)
    return (
        f"// {HEADER}\n\n"
        "/** Each provider's model catalog, as the bytes of its spec file. */\n"
        f"export const MODEL_CATALOGS: readonly string[] = [\n{items}];\n"
    )


def main(argv: list[str]) -> int:
    if argv:
        print(__doc__)
        return 2
    texts = catalogs()
    for path, text in ((PYTHON, python(texts)), (TYPESCRIPT, typescript(texts))):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
