#!/usr/bin/env python3
# pyright: strict
"""Generate the TypeScript API surface checks from spec/api.json and the gaps registry.

    python3 spec/tools/gen_api_surface.py                  # write the generated file
    python3 spec/tools/gen_api_surface.py --api A --gaps G --out F

Stdlib only. The output is not committed (scripts/generate.sh writes it) and is compiled by
`tsc -p packages/core/test/api-surface` in `bun run typecheck`. Each contract member becomes
Assert lines (api-surface/helpers.ts) that tsc fails when the package disagrees with the
contract. A listed TypeScript gap is asserted too (the member is absent, or its required flag is
the other one), so a fixed gap fails to compile until its entry is deleted: the registry only
shrinks.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import TYPE_CHECKING

from surface_contract import Gap, Member, members, obj, parse_gaps

if TYPE_CHECKING:
    from check_api import Json

ROOT = pathlib.Path(__file__).resolve().parents[2]
API = ROOT / "spec" / "api.json"
GAPS = ROOT / "spec" / "api-surface-gaps.json"
OUT = ROOT / "typescript/packages/core/test/api-surface/generated/surface.ts"
HEADER = (
    "// Generated by spec/tools/gen_api_surface.py from spec/api.json and "
    "spec/api-surface-gaps.json. Do not edit."
)
MARKER = "__surfaceGap"
HELPERS = (
    "Assert", "AtMostFiveOverloads", "Equals", "HasKey", "IsCallable", "IsMissing",
    "OptionPresent", "OptionRequired", "Req",
)  # fmt: skip


class Emitter:
    """The Assert lines for one contract and its TypeScript gaps."""

    def __init__(self, contract: dict[str, Member], gaps: list[Gap]) -> None:
        self.contract = contract
        self.gaps = {g.name: g for g in gaps}
        self.lines: list[str] = []
        self.absent_types: dict[str, list[str]] = {}

    def gap(self, m: Member) -> str | None:
        gap = self.gaps.get(m.name)
        return gap.kind if gap else None

    def _out(self, m: Member, what: str, check: str) -> None:
        """One line, named after the member and what it checks, so a tsc error reads as both."""
        ident = re.sub(r"\W", "_", m.name)
        self.lines.append(f"export type {m.role}_{ident}_{what} = {check};")

    def _usable(self, m: Member) -> bool:
        """A member is checked only when its owner (and the owner's owner) resolves: exported
        from its declared entry, or from the entry a placement gap names."""
        parent = self.contract.get(m.parent)
        if parent is None:
            return True
        gap = self.gaps.get(parent.name)
        return (gap is None or gap.at is not None) and self._usable(parent)

    def type_ref(self, name: str) -> str:
        """The type as the generated file reaches it: from the entry a placement gap names, or
        from its declared entry."""
        t, gap = self.contract[name], self.gaps.get(name)
        args = f"<{', '.join(['never'] * t.generics)}>" if t.generics else ""
        return f"{gap.at if gap and gap.at else t.package}.{t.ts}{args}"

    def callable_ref(self, m: Member) -> str:
        if m.role == "function":
            return f"typeof {m.package}.{m.ts}"
        return f'{self.type_ref(m.parent)}["{m.ts}"]'

    def keyed(self, m: Member, owner: str) -> None:
        """A function, property, field or method: present, its required flag, and a function
        or method is callable."""
        kind, key = self.gap(m), f'"{m.ts}"'
        if kind == "missing":
            self._out(m, "missing", f"Assert<IsMissing<{owner}, {key}>>")
            return
        self._out(m, "present", f"Assert<HasKey<{owner}, {key}>>")
        if m.role != "function":
            flip = kind == "required_mismatch"
            self._out(
                m, "required", f"Assert<Equals<Req<{owner}, {key}>, {_ts(m.required != flip)}>>"
            )
        if m.role in ("function", "method"):
            self._out(m, "callable", f"Assert<IsCallable<{self.callable_ref(m)}>>")
            self._out(m, "overloads", f"Assert<AtMostFiveOverloads<{self.callable_ref(m)}>>")

    def option(self, m: Member) -> None:
        parent = self.contract[m.parent]
        fn, key = self.callable_ref(parent), f'"{m.ts}"'
        at = f"{fn}, {parent.positional}, {key}"
        kind = self.gap(m)
        self._out(m, "present", f"Assert<Equals<OptionPresent<{at}>, {_ts(kind != 'missing')}>>")
        if kind != "missing":
            flip = kind == "required_mismatch"
            self._out(
                m, "required", f"Assert<Equals<OptionRequired<{at}>, {_ts(m.required != flip)}>>"
            )

    def member(self, m: Member) -> None:
        if "ts" not in m.langs or not self._usable(m):
            return
        if m.role == "type":
            if self.gap(m) is None:
                self._out(m, "exported", self.type_ref(m.name))
            else:
                self.absent_types.setdefault(m.package, []).append(m.ts)
                self.placed(m)
        elif m.role == "option":
            self.option(m)
        elif m.role == "function":
            self.keyed(m, f"typeof {m.package}")
        else:
            self.keyed(m, self.type_ref(m.parent))

    def placed(self, m: Member) -> None:
        """A placement gap names the entry that exports the type instead: it must be there."""
        gap = self.gaps[m.name]
        if gap.at:
            self._out(m, f"at_{gap.at}", self.type_ref(m.name))

    def augmentations(self, packages: dict[str, str]) -> list[str]:
        """A listed missing type is declared into its package as a type alias: that compiles
        only while the package has no type of that name (an alias can't merge with anything, so
        any existing interface, alias or class, even an empty one, is a duplicate)."""
        out: list[str] = []
        for package, names in sorted(self.absent_types.items()):
            out.append(f'declare module "{packages[package]}" {{')
            out += [f"  type {n} = {{ readonly {MARKER}: true }};" for n in sorted(names)]
            out.append("}")
            out += [
                f'export type type_{n}_missing = Assert<Equals<keyof {package}.{n}, "{MARKER}">>;'
                for n in sorted(names)
            ]
        return out


def _ts(flag: bool) -> str:
    return "true" if flag else "false"


def render(api: Json, gaps_doc: Json) -> str:
    contract = members(api)
    gaps, errs = parse_gaps(gaps_doc, contract, "api-surface-gaps.json")
    if errs:
        raise SystemExit("\n".join(errs))
    emitter = Emitter(contract, [g for g in gaps if g.lang == "ts"])
    for m in contract.values():
        emitter.member(m)
    packages = {k: str(obj(v).get("ts")) for k, v in obj(obj(api).get("packages")).items()}
    helpers = ", ".join(HELPERS)
    head = [HEADER, f'import type {{ {helpers} }} from "../helpers";']
    head += [f'import type * as {k} from "{v}";' for k, v in sorted(packages.items())]
    return "\n".join([*head, "", *emitter.augmentations(packages), *emitter.lines, ""])


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api", type=pathlib.Path, default=API)
    parser.add_argument("--gaps", type=pathlib.Path, default=GAPS)
    parser.add_argument("--out", type=pathlib.Path, default=OUT)
    args = parser.parse_args(argv)
    api_path: pathlib.Path = args.api
    gaps_path: pathlib.Path = args.gaps
    out: pathlib.Path = args.out
    api: Json = json.loads(api_path.read_text())
    gaps: Json = json.loads(gaps_path.read_text())
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(api, gaps))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
