import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { verifyExport } from "@threads/core";
import type { ChainEvent } from "@threads/core/internal/feed";
import { z } from "zod";
import { body } from "../src/otlp";
import type { Span } from "../src/span";
import { spans } from "../src/spans";

// The spec/otel goldens (generated by spec/tools/fixtures/otel.py), read as data.

export const OTEL: string = join(import.meta.dir, "../../../../spec/otel");

const Sync = z.strictObject({
  branch_id: z.string(),
  head_seq: z.int(),
  cursor_before: z.int(),
  cursor_after: z.int(),
  spans: z.int(),
  expected: z.string().optional(),
});

const Case = z.strictObject({
  name: z.string(),
  description: z.string(),
  tenant: z.string(),
  content: z.boolean(),
  resource: z.record(z.string(), z.string()),
  scope_version: z.string(),
  branches: z.array(z.string()),
  syncs: z.array(Sync),
});
type SyncPlan = {
  readonly branch_id: string;
  readonly head_seq: number;
  readonly cursor_before: number;
  readonly cursor_after: number;
  readonly spans: number;
  readonly expected?: string | undefined;
};

export type Golden = {
  readonly name: string;
  readonly tenant: string;
  readonly content: boolean;
  readonly resource: Readonly<Record<string, string>>;
  readonly scope_version: string;
  readonly branches: readonly string[];
  readonly syncs: readonly SyncPlan[];
  readonly dir: string;
  readonly chains: ReadonlyMap<string, readonly ChainEvent[]>;
};

export function goldens(): readonly Golden[] {
  const root = join(OTEL, "cases");
  return readdirSync(root)
    .toSorted()
    .map((name) => {
      const dir = join(root, name);
      const c = Case.parse(
        JSON.parse(readFileSync(join(dir, "case.json"), "utf8")),
      );
      const chains = new Map(
        c.branches.map((b) => {
          const log = verifyExport(readFileSync(join(dir, `${b}.jsonl`)));
          if (!log.ok)
            throw new Error(
              `${name}/${b}: ${log.error.code} ${log.error.message}`,
            );
          return [b, log.value.events] as const;
        }),
      );
      return { ...c, dir, chains };
    });
}

export function through(
  chain: readonly ChainEvent[],
  head: number,
): readonly ChainEvent[] {
  return chain.filter((line) => line.event.seq <= head);
}

/** The spans one sync of a golden sends: those closing in (cursor, head]. */
export function synced(
  g: Golden,
  branchId: string,
  cursor: number,
  head: number,
): readonly Span[] {
  const chain = g.chains.get(branchId) ?? [];
  const all = spans(
    {
      tenant: g.tenant,
      branchId,
      chain: through(chain, head),
      content: g.content,
    },
    (id) => g.chains.get(id),
  );
  return all.filter((s) => s.closeSeq > cursor && s.closeSeq <= head);
}

export function expectedBody(
  g: Golden,
  file: string | undefined,
): string | undefined {
  return file === undefined
    ? undefined
    : readFileSync(join(g.dir, file), "utf8");
}

export function encode(g: Golden, sent: readonly Span[]): string | undefined {
  return sent.length === 0
    ? undefined
    : body(sent, g.resource, g.scope_version);
}
