"""The shared A2A vector (spec/conformance/vectors/a2a.json), generated by
spec/tools/fixtures/a2a_vectors.py from the pinned protocol. TypeScript runs the same five tables
over its own implementation (typescript/packages/a2a/test/vectors.test.ts), which is what proves
the two agree without either reading the other's code. Each table asserts the guarantee, never how
this side reaches it."""

from pathlib import Path

import pytest
from pydantic import JsonValue, TypeAdapter, ValidationError

from threads._generated.a2a_v1 import TaskState
from threads.a2a.protocol import (
    A2A_ERROR_NAMES,
    A2A_ERRORS,
    check_version,
    inbound_path,
    is_interrupted,
    is_terminal,
    sse_events_of,
)

VECTORS = Path(__file__).resolve().parents[3] / "spec" / "conformance" / "vectors"
type Row = dict[str, JsonValue]
_DOC: TypeAdapter[dict[str, list[Row]]] = TypeAdapter(dict[str, list[Row]])
_TABLES = _DOC.validate_json((VECTORS / "a2a.json").read_bytes())
# The state a peer sends is untyped until the generated model accepts it, which is the boundary
# TypeScript's TaskState.safeParse is; `is_terminal` only ever sees a value that passed it.
_STATE: TypeAdapter[TaskState] = TypeAdapter(TaskState)


def _rows(table: str) -> list[Row]:
    rows = _TABLES[table]
    assert rows, f"a2a.json: the {table} table is empty"
    return rows


def _name(row: Row) -> str:
    return str(row["name"])


def _text(value: JsonValue) -> str | None:
    return value if isinstance(value, str) else None


def test_the_error_table_names_every_error_we_answer_with() -> None:
    assert sorted(_name(r) for r in _rows("errors")) == sorted(A2A_ERROR_NAMES)


@pytest.mark.parametrize("row", _rows("errors"), ids=_name)
def test_an_error_code_and_status(row: Row) -> None:
    # Looked up by walking the table, so the row's name being one of ours is part of the assertion.
    coded = [c for name, c in A2A_ERRORS.items() if name == _name(row)]
    assert coded, f"{_name(row)} is not an A2A error"
    assert (coded[0].code, coded[0].status) == (row["code"], row["status"])


@pytest.mark.parametrize("row", _rows("task_states"), ids=_name)
def test_a_task_state(row: Row) -> None:
    try:
        state = _STATE.validate_python(row["state"])
    except ValidationError:
        assert row["accepted"] is False
        return
    assert row["accepted"] is True
    assert is_terminal(state) is row["terminal"]
    assert is_interrupted(state) is row["interrupted"]


@pytest.mark.parametrize("row", _rows("versions"), ids=_name)
def test_a_declared_version(row: Row) -> None:
    accepted = check_version(_text(row["header"]), _text(row["query"])) is None
    assert accepted is row["accepted"]


@pytest.mark.parametrize("row", _rows("paths"), ids=_name)
def test_an_inbound_path(row: Row) -> None:
    found = inbound_path(str(row["path"]))
    named = (None, None) if found is None else (found.method, found.id)
    assert named == (row["method"], row["id"])


@pytest.mark.parametrize("row", _rows("sse"), ids=_name)
def test_an_sse_body(row: Row) -> None:
    read = [{"id": e.id, "data": e.data} for e in sse_events_of(str(row["raw"]))]
    assert read == row["events"]
