"""The host API's request and receipt models (spec/schema/host-api/host-api.v1.schema.json).

Its shapes reference the event schema by URN. The generator sees one combined schema, the
normalized event $defs plus the host shapes named in HOST_SHAPES with their URN refs made local,
and every model the event schema already defines is then dropped from the output and imported
from `events_v1` instead, so each event type has exactly one Python class.
"""

import ast
import json
from pathlib import Path

from schema_normalize import Json, Obj, as_obj, normalize

SPEC = Path(__file__).resolve().parent.parent.parent / "spec" / "schema"
HOST_SCHEMA = SPEC / "host-api" / "host-api.v1.schema.json"
CASE_SCHEMA = SPEC.parent / "conformance" / "case.schema.json"
EVENTS_URN = "urn:threads:schema:events:v1#/$defs/"
CONFORMANCE_URN = "urn:threads:schema:conformance:v1#/$defs/"
HOST_SHAPES = (
    "Input",
    "StartRunRequest",
    "RunAccepted",
    "BranchRef",
    "BranchInfo",
    "ForkRequest",
    "PendingApproval",
    "ApprovalDecision",
    "Answer",
    "ParkedResolution",
    "SettingsChange",
    "ModeChange",
    "Appended",
    "Cost",
    "CacheBreak",
)
"""The boundary shapes: request bodies the host parses and the receipts it returns, and the
projections that are whole conformance $defs (Cost, CacheBreak), inlined. Projections that
reference other schemas' nested paths (RunOutcome, Timeline) are built from core types."""
HEADER = (
    "# Generated by python/tools/regen_models.py from\n"
    "# spec/schema/host-api/host-api.v1.schema.json. Do not edit by hand.\n"
    "# pyright: reportPrivateUsage=false\n"
    "# (the constrained id aliases are the event module's private names)"
)


def _local_refs(node: Json) -> Json:
    if isinstance(node, dict):
        return {
            k: v.replace(EVENTS_URN, "#/$defs/")
            if k == "$ref" and isinstance(v, str)
            else _local_refs(v)
            for k, v in node.items()
        }
    if isinstance(node, list):
        return [_local_refs(v) for v in node]
    return node


def _inlined(shape: Json, cases: Obj) -> Json:
    """A host shape that is only a $ref to a conformance $def, as that $def."""
    ref = as_obj(shape).get("$ref")
    if isinstance(ref, str) and ref.startswith(CONFORMANCE_URN):
        return cases[ref.removeprefix(CONFORMANCE_URN)]
    return shape


def combined_schema(events: Obj) -> Obj:
    normalized = normalize(events)
    defs = dict(as_obj(normalized["$defs"]))
    host = as_obj(as_obj(json.loads(HOST_SCHEMA.read_text(encoding="utf-8")))["$defs"])
    cases = as_obj(as_obj(json.loads(CASE_SCHEMA.read_text(encoding="utf-8")))["$defs"])
    for name in HOST_SHAPES:
        if name in defs:
            raise SystemExit(f"regen: host shape {name} collides with an event $def")
        defs[name] = _local_refs(_inlined(host[name], cases))
    return {**normalized, "$defs": defs}


def _defined(node: ast.stmt) -> str | None:
    match node:
        case ast.ClassDef(name=name) | ast.TypeAlias(name=ast.Name(id=name)):
            return name
        case ast.Assign(targets=[ast.Name(id=name)]):
            return name
        case _:
            return None


def keep_host_shapes(source: str, event_names: frozenset[str]) -> str:
    """Drops every top-level definition the event module owns, with its docstring, and imports
    the ones the kept shapes use."""
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    drop: list[tuple[int, int]] = []
    body = tree.body
    for i, node in enumerate(body):
        name = _defined(node)
        if name is None or name not in event_names:
            continue
        end = node.end_lineno or node.lineno
        after = body[i + 1] if i + 1 < len(body) else None
        is_doc = isinstance(after, ast.Expr) and isinstance(after.value, ast.Constant)
        if after is not None and is_doc and not isinstance(node, ast.ClassDef):
            end = after.end_lineno or end
        drop.append((node.lineno, end))
    dropped = {n for n in (_defined(b) for b in body) if n in event_names}
    kept = [
        line
        for number, line in enumerate(lines, 1)
        if not any(start <= number <= end for start, end in drop)
    ]
    text = "".join(kept)
    used = sorted(n for n in dropped if f"{n}" in _names(text))
    imports = f"from threads._generated.events_v1 import {', '.join(used)}\n"
    return text.replace(
        "from threads._strict_model import", imports + "from threads._strict_model import", 1
    )


def _names(source: str) -> set[str]:
    return {n.id for n in ast.walk(ast.parse(source)) if isinstance(n, ast.Name)}


def defined_names(source: str) -> frozenset[str]:
    """Every top-level name a generated module defines."""
    return frozenset(n for n in (_defined(b) for b in ast.parse(source).body) if n is not None)
