"""Regenerates the Pydantic models for the event log from the committed JSON Schema.

    uv run python tools/regen_models.py          # rewrite src/threads/_generated/events_v1.py
    uv run python tools/regen_models.py --check  # exit 1 if the committed file is stale

Pipeline: `schema_normalize` rewrites the schema into an equivalent generator-friendly form,
datamodel-codegen (pinned in the dev group) emits the models with the flags below, and
`brand_ids` turns the id aliases into `NewType` brands. The output is ruff-formatted, so the
comparison is byte-exact.
"""

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from schema_normalize import Obj, as_obj, normalize

PYTHON_DIR = Path(__file__).resolve().parent.parent
SCHEMA = PYTHON_DIR.parent / "spec" / "schema" / "events.v1.schema.json"
OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "events_v1.py"
BRANDED = ("EventId", "ThreadId", "BranchId", "CallId")
HEADER = (
    "# Generated by python/tools/regen_models.py from spec/schema/events.v1.schema.json.\n"
    "# Do not edit by hand: change the schema and regenerate."
)
GENERATOR_FLAGS = (
    "--input-file-type=jsonschema",
    "--output-model-type=pydantic_v2.BaseModel",
    "--target-python-version=3.12",
    "--target-pydantic-version=2.12",
    "--base-class=threads._strict_model.StrictModel",
    "--extra-fields=forbid",
    "--enable-faux-immutability",
    "--strict-types",
    "str",
    "bytes",
    "int",
    "float",
    "bool",
    "--use-annotated",
    "--field-constraints",
    "--enum-field-as-literal=all",
    "--use-type-alias",
    "--use-missing-sentinel",
    "--use-generic-container-types",
    "--use-standard-collections",
    '--type-overrides={"JsonValue": "pydantic.JsonValue"}',
    "--model-extra-keys-without-x-prefix",
    "x-allOf",
    "--skip-root-model",
    "--use-schema-description",
    "--use-field-description",
    "--disable-timestamp",
    "--disable-future-imports",
    "--use-double-quotes",
    "--use-exact-imports",
    "--formatters",
    "ruff-format",
)


def brand_ids(source: str) -> str:
    """Rewrites `EventId = Annotated[StrictStr, ...]` into a NewType brand plus a private
    constrained alias used by the fields, so the pattern stays in the generated code."""
    for name in BRANDED:
        source = re.sub(rf"\b{name}\b", f"_{name}", source)
        source = re.sub(
            rf"^(type )?_{name}( = )Annotated\[\s*StrictStr,",
            rf'{name} = NewType("{name}", str)\n\1_{name}\2Annotated[{name},',
            source,
            count=1,
            flags=re.MULTILINE,
        )
        if f'{name} = NewType("{name}", str)' not in source:
            raise SystemExit(f"regen: could not brand {name}; generator output changed shape")
    return source.replace("from typing import ", "from typing import NewType, ", 1)


def annotate_config(source: str) -> str:
    """Declares `model_config` as a ClassVar like BaseModel does; unannotated overrides make
    the public types ambiguous to `pyright --verifytypes`."""
    source = source.replace(
        "    model_config = ConfigDict(", "    model_config: ClassVar[ConfigDict] = ConfigDict("
    )
    return source.replace("from typing import ", "from typing import ClassVar, ", 1)


def add_exports(source: str) -> str:
    """Lists every public model and alias in `__all__` so `threads.log` can re-export them."""
    names = re.findall(
        r"^(?:class ([A-Z]\w*)\(|type ([A-Z]\w*) = |([A-Z]\w*) = NewType\()",
        source,
        flags=re.MULTILINE,
    )
    names = ["".join(groups) for groups in names]
    return f"{source}\n\n__all__ = {sorted(set(names))!r}\n"


def generate(workdir: Path) -> str:
    normalized = workdir / "events.v1.normalized.json"
    schema: Obj = as_obj(json.loads(SCHEMA.read_text(encoding="utf-8")))
    normalized.write_text(json.dumps(normalize(schema), indent=2), encoding="utf-8")
    raw = workdir / "raw.py"
    subprocess.run(  # noqa: S603 - fixed argv, no shell
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            f"--input={normalized}",
            f"--output={raw}",
            f"--custom-file-header={HEADER}",
            *GENERATOR_FLAGS,
        ],
        check=True,
    )
    source = add_exports(annotate_config(brand_ids(raw.read_text(encoding="utf-8"))))
    source = ruff(source, "check", "--fix", "--select=I")
    return ruff(source, "format")


def ruff(source: str, *command: str) -> str:
    done = subprocess.run(  # noqa: S603 - fixed argv, no shell
        [sys.executable, "-m", "ruff", *command, "--quiet", f"--stdin-filename={OUTPUT}", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
        cwd=PYTHON_DIR,
    )
    return done.stdout


def main(argv: list[str]) -> int:
    check = argv == ["--check"]
    if argv and not check:
        print(__doc__)
        return 2
    with tempfile.TemporaryDirectory() as tmp:
        fresh = generate(Path(tmp))
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if check:
        if fresh != current:
            print(f"{OUTPUT.relative_to(PYTHON_DIR)} is stale: run tools/regen_models.py")
            return 1
        return 0
    OUTPUT.write_text(fresh, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
