"""Regenerates the Pydantic models from the committed JSON Schemas: the event log
(events_v1.py), the built-in tool inputs plus their canonical catalog (tools_v1.py), the host API
(host_api_v1.py), the model catalog file shape (model_catalog_v1.py) and the tree artifact
(tree_v1.py).

    uv run python tools/regen_models.py          # rewrite src/threads/_generated/*_v1.py
    uv run python tools/regen_models.py --check  # exit 1 if a committed file is stale

Pipeline: `schema_normalize` rewrites the schema into an equivalent generator-friendly form,
datamodel-codegen (pinned in the dev group) emits the models with the flags below, and
`brand_ids` turns the id aliases into `NewType` brands. The output is ruff-formatted, so the
comparison is byte-exact.
"""

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from eval_models import HEADER as EVAL_HEADER
from eval_models import combined_eval_schema
from host_api_models import HEADER as HOST_HEADER
from host_api_models import combined_schema, defined_names, keep_host_shapes, open_shapes
from schema_normalize import Normalizer, Obj, as_obj, normalize

PYTHON_DIR = Path(__file__).resolve().parent.parent
SCHEMA = PYTHON_DIR.parent / "spec" / "schema" / "events.v1.schema.json"
OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "events_v1.py"
TOOLS_SCHEMA = PYTHON_DIR.parent / "spec" / "schema" / "tools.v1.schema.json"
TOOLS_CATALOG = PYTHON_DIR.parent / "spec" / "schema" / "tools.v1.catalog.json"
TOOLS_OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "tools_v1.py"
HOST_OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "host_api_v1.py"
EVAL_OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "eval_v1.py"
CATALOG_SCHEMA = PYTHON_DIR.parent / "spec" / "schema" / "model-catalog.v1.schema.json"
CATALOG_OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "model_catalog_v1.py"
CATALOG_HEADER = (
    "# Generated by python/tools/regen_models.py from spec/schema/model-catalog.v1.schema.json.\n"
    "# Do not edit by hand: change the Zod schema, run bun run schema:export, and regenerate."
)
TREE_SCHEMA = PYTHON_DIR.parent / "spec" / "schema" / "tree.v1.schema.json"
TREE_OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "tree_v1.py"
TREE_HEADER = (
    "# Generated by python/tools/regen_models.py from spec/schema/tree.v1.schema.json.\n"
    "# Do not edit by hand: change the Zod schema, run bun run schema:export, and regenerate."
)
BUNDLE_SCHEMA = PYTHON_DIR.parent / "spec" / "schema" / "bundle.v1.schema.json"
BUNDLE_OUTPUT = PYTHON_DIR / "src" / "threads" / "_generated" / "bundle_v1.py"
BUNDLE_HEADER = (
    "# Generated by python/tools/regen_models.py from spec/schema/bundle.v1.schema.json.\n"
    "# Do not edit by hand: change the Zod schema, run bun run schema:export, and regenerate."
)
TOOLS_HEADER = (
    "# Generated by python/tools/regen_models.py from spec/schema/tools.v1.schema.json and\n"
    "# spec/schema/tools.v1.catalog.json. Do not edit by hand: change the TypeScript catalog,\n"
    "# run bun run schema:export, and regenerate."
)
BRANDED = ("EventId", "ThreadId", "BranchId", "CallId")
HEADER = (
    "# Generated by python/tools/regen_models.py from spec/schema/events.v1.schema.json.\n"
    "# Do not edit by hand: change the schema and regenerate."
)
GENERATOR_FLAGS = (
    "--input-file-type=jsonschema",
    "--output-model-type=pydantic_v2.BaseModel",
    "--target-python-version=3.12",
    "--target-pydantic-version=2.12",
    "--base-class=threads._strict_model.StrictModel",
    "--extra-fields=forbid",
    "--enable-faux-immutability",
    "--strict-types",
    "str",
    "bytes",
    "int",
    "float",
    "bool",
    "--use-annotated",
    "--field-constraints",
    "--enum-field-as-literal=all",
    "--use-type-alias",
    "--use-missing-sentinel",
    "--use-generic-container-types",
    "--use-standard-collections",
    '--type-overrides={"JsonValue": "pydantic.JsonValue"}',
    "--model-extra-keys-without-x-prefix",
    "x-allOf",
    "--skip-root-model",
    "--use-schema-description",
    "--use-field-description",
    "--disable-timestamp",
    "--disable-future-imports",
    "--use-double-quotes",
    "--use-exact-imports",
    "--formatters",
    "ruff-format",
)


def brand_ids(source: str) -> str:
    """Rewrites `EventId = Annotated[StrictStr, ...]` into a NewType brand plus a private
    constrained alias used by the fields, so the pattern stays in the generated code."""
    for name in BRANDED:
        source = re.sub(rf"\b{name}\b", f"_{name}", source)
        source = re.sub(
            rf"^(type )?_{name}( = )Annotated\[\s*StrictStr,",
            rf'{name} = NewType("{name}", str)\n\1_{name}\2Annotated[{name},',
            source,
            count=1,
            flags=re.MULTILINE,
        )
        if f'{name} = NewType("{name}", str)' not in source:
            raise SystemExit(f"regen: could not brand {name}; generator output changed shape")
    return source.replace("from typing import ", "from typing import NewType, ", 1)


def annotate_config(source: str) -> str:
    """Declares `model_config` as a ClassVar like BaseModel does; unannotated overrides make
    the public types ambiguous to `pyright --verifytypes`."""
    source = source.replace(
        "    model_config = ConfigDict(", "    model_config: ClassVar[ConfigDict] = ConfigDict("
    )
    return source.replace("from typing import ", "from typing import ClassVar, ", 1)


def add_exports(source: str) -> str:
    """Lists every public model and alias in `__all__` so `threads.log` can re-export them."""
    names = re.findall(
        r"^(?:class ([A-Z]\w*)\(|type ([A-Z]\w*) = |([A-Z]\w*) = NewType\()",
        source,
        flags=re.MULTILINE,
    )
    names = ["".join(groups) for groups in names]
    return f"{source}\n\n__all__ = {sorted(set(names))!r}\n"


def codegen(schema: Path, raw: Path, header: str, *extra: str) -> str:
    subprocess.run(  # noqa: S603 - fixed argv, no shell
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            f"--input={schema}",
            f"--output={raw}",
            f"--custom-file-header={header}",
            *GENERATOR_FLAGS,
            *extra,
        ],
        check=True,
    )
    return raw.read_text(encoding="utf-8")


def generate(workdir: Path) -> str:
    normalized = workdir / "events.v1.normalized.json"
    schema: Obj = as_obj(json.loads(SCHEMA.read_text(encoding="utf-8")))
    normalized.write_text(json.dumps(normalize(schema), indent=2), encoding="utf-8")
    raw = codegen(normalized, workdir / "raw.py", HEADER)
    source = add_exports(annotate_config(brand_ids(raw)))
    source = ruff(source, "check", "--fix", "--select=I")
    return ruff(source, "format")


def generate_host_api(workdir: Path, events_source: str) -> str:
    """The host API's boundary shapes, importing every event type from events_v1."""
    combined = workdir / "host-api.combined.json"
    schema: Obj = as_obj(json.loads(SCHEMA.read_text(encoding="utf-8")))
    combined.write_text(json.dumps(combined_schema(schema), indent=2), encoding="utf-8")
    raw = annotate_config(brand_ids(codegen(combined, workdir / "host.py", HOST_HEADER)))
    source = add_exports(open_shapes(keep_host_shapes(raw, defined_names(events_source))))
    # The dropped event models leave some of the generator's imports unused.
    source = ruff(source, "check", "--fix", "--select=I,F401")
    return ruff(source, "format")


def generate_eval(workdir: Path, events_source: str) -> str:
    """The eval runner's shapes, importing every event type from events_v1."""
    combined = workdir / "eval.combined.json"
    schema: Obj = as_obj(json.loads(SCHEMA.read_text(encoding="utf-8")))
    combined.write_text(json.dumps(combined_eval_schema(schema), indent=2), encoding="utf-8")
    raw = annotate_config(brand_ids(codegen(combined, workdir / "eval.py", EVAL_HEADER)))
    source = add_exports(keep_host_shapes(raw, defined_names(events_source)))
    source = ruff(source, "check", "--fix", "--select=I,F401")
    return ruff(source, "format")


def generate_tools(workdir: Path) -> str:
    """Tool input models (a default is a value, never null: --strict-nullable) and the catalog
    bytes line 0 pins, embedded so the runtime reads no file under spec/."""
    raw = codegen(TOOLS_SCHEMA, workdir / "tools.py", TOOLS_HEADER, "--strict-nullable")
    catalog = TOOLS_CATALOG.read_text(encoding="utf-8")
    if "\\" in catalog or '"""' in catalog:
        raise SystemExit("regen: the tool catalog can't hold a backslash or triple quote")
    source = annotate_config(raw).replace("from typing import ", "from typing import Final, ", 1)
    # One line of JCS, so it is longer than any line limit.
    source += f'\n\nTOOL_CATALOG: Final[str] = """{catalog}"""  # noqa: E501\n'
    source = add_exports(source).replace("__all__ = [", "__all__ = ['TOOL_CATALOG', ", 1)
    source = ruff(source, "check", "--fix", "--select=I")
    return ruff(source, "format")


def generate_rooted(workdir: Path, schema: Path, name: str, header: str) -> str:
    """A file shape whose root object moves under $defs, so --skip-root-model keeps it as a
    class called `name`: the model catalog (spec/models/<provider>.v1.json) and the tree."""
    root: Obj = as_obj(json.loads(schema.read_text(encoding="utf-8")))
    defs = as_obj(root.get("$defs", {}))
    body = {k: v for k, v in root.items() if k not in ("$id", "$schema", "$defs")}
    # Unions of tagged objects get their discriminator, as the events' unions do.
    tagged = Normalizer({"$defs": defs})
    for node in defs.values():
        tagged.add_discriminator(as_obj(node))
    wrapped = workdir / f"{name}.json"
    wrapped.write_text(json.dumps({"$defs": {**defs, name: body}}), encoding="utf-8")
    raw = codegen(wrapped, workdir / f"{name}.py", header)
    source = add_exports(annotate_config(raw))
    source = ruff(source, "check", "--fix", "--select=I")
    return ruff(source, "format")


def ruff(source: str, *command: str) -> str:
    done = subprocess.run(  # noqa: S603 - fixed argv, no shell
        [sys.executable, "-m", "ruff", *command, "--quiet", f"--stdin-filename={OUTPUT}", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
        cwd=PYTHON_DIR,
    )
    return done.stdout


def main(argv: list[str]) -> int:
    check = argv == ["--check"]
    if argv and not check:
        print(__doc__)
        return 2
    stale = 0
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        events = generate(work)
        builds = (
            (OUTPUT, lambda: events),
            (TOOLS_OUTPUT, lambda: generate_tools(work)),
            (HOST_OUTPUT, lambda: generate_host_api(work, events)),
            (EVAL_OUTPUT, lambda: generate_eval(work, events)),
            (
                CATALOG_OUTPUT,
                lambda: generate_rooted(work, CATALOG_SCHEMA, "ModelCatalog", CATALOG_HEADER),
            ),
            (TREE_OUTPUT, lambda: generate_rooted(work, TREE_SCHEMA, "Tree", TREE_HEADER)),
            (
                BUNDLE_OUTPUT,
                lambda: generate_rooted(work, BUNDLE_SCHEMA, "Bundle", BUNDLE_HEADER),
            ),
        )
        for output, build in builds:
            fresh = build()
            current = output.read_text(encoding="utf-8") if output.exists() else ""
            if not check:
                output.write_text(fresh, encoding="utf-8")
            elif fresh != current:
                print(f"{output.relative_to(PYTHON_DIR)} is stale: run tools/regen_models.py")
                stale = 1
    return stale


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
