// Generates content/docs/http-api/ from openapi.json (itself generated by gen_api_ref.py).
// Deterministic: the same openapi.json always writes the same bytes.
//
//   bun scripts/gen-openapi.ts          # write content/docs/http-api/
//   bun scripts/gen-openapi.ts --check  # exit 1 if anything is out of date
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { generateFilesOnly } from "fumadocs-openapi";
import { openapi } from "../lib/openapi";

const OUT = "./content/docs/http-api";

const slugify = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

type Spec = { paths: Record<string, Record<string, { operationId?: string }>> };
const spec: Spec = JSON.parse(await readFile("./openapi.json", "utf8"));
// Sidebar order follows the order of routes in the OpenAPI file.
const order = Object.values(spec.paths)
  .flatMap((item) => Object.values(item))
  .flatMap((op) => (op.operationId ? [slugify(op.operationId)] : []));

const INDEX = `---
title: HTTP API
description: The host's typed JSON API, generated from its OpenAPI file.
icon: Globe
---

{/* Generated by scripts/gen-openapi.ts. Do not edit. */}

Every [host](/docs/host/overview) serves this API under \`/v1\`, plus the channel webhooks. The pages are generated
from \`spec/schema/host-api/openapi.json\`. For authentication, streaming and retries, read the
[HTTP API guide](/docs/host/http-api) first.

The examples use \`http://localhost:8787\`, the address \`threads dev\` serves on.
`;

const META = `${JSON.stringify(
  {
    title: "HTTP API",
    description: "Host routes",
    icon: "Globe",
    root: true,
    pages: ["index", ...order],
  },
  null,
  2,
)}\n`;

const generated = await generateFilesOnly({
  input: openapi,
  per: "operation",
  name(output) {
    if (output.type !== "operation") throw new Error("the host API has no webhooks");
    const op = spec.paths[output.item.path]?.[output.item.method];
    if (!op?.operationId) throw new Error(`no operationId: ${output.item.path}`);
    return slugify(op.operationId);
  },
  includeDescription: true,
  addGeneratedComment: "Generated by scripts/gen-openapi.ts from openapi.json. Do not edit.",
});

const files = new Map<string, string>([
  ["index.mdx", INDEX],
  ["meta.json", META],
  ...generated.map((f): [string, string] => [f.path, f.content]),
]);

if (process.argv.includes("--check")) {
  const existing = new Set(await readdir(OUT).catch(() => []));
  const stale = [...existing].filter((name) => !files.has(name));
  const changed: string[] = [];
  for (const [name, content] of files) {
    const current = await readFile(join(OUT, name), "utf8").catch(() => null);
    if (current !== content) changed.push(name);
  }
  for (const name of [...changed, ...stale]) console.log(`out of date: ${join(OUT, name)}`);
  process.exit(changed.length + stale.length > 0 ? 1 : 0);
}

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });
for (const [name, content] of files) await writeFile(join(OUT, name), content);
console.log(`wrote ${files.size} file(s) to ${OUT}`);
