import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import {
  A2A_ERROR_NAMES,
  A2A_ERRORS,
  checkVersion,
  inboundPath,
  isInterrupted,
  isTerminal,
  sseEvents,
  TaskState,
} from "../src/protocol";

// The shared A2A vector (spec/conformance/vectors/a2a.json), generated by
// spec/tools/fixtures/a2a_vectors.py from the pinned protocol. Python runs the same five tables
// over its own implementation, which is what proves the two agree without either reading the
// other's code. Each table asserts the guarantee, never how this side reaches it.

const FILE = join(
  import.meta.dir,
  "../../../../spec/conformance/vectors/a2a.json",
);

const Doc = z.object({
  errors: z.array(
    z.object({ name: z.string(), code: z.number(), status: z.number() }),
  ),
  task_states: z.array(
    z.object({
      name: z.string(),
      state: z.string(),
      accepted: z.boolean(),
      terminal: z.boolean().optional(),
      interrupted: z.boolean().optional(),
    }),
  ),
  versions: z.array(
    z.object({
      name: z.string(),
      header: z.string().nullable(),
      query: z.string().nullable(),
      accepted: z.boolean(),
    }),
  ),
  paths: z.array(
    z.object({
      name: z.string(),
      path: z.string(),
      method: z.string().nullable(),
      id: z.string().nullable(),
    }),
  ),
  sse: z.array(
    z.object({
      name: z.string(),
      raw: z.string(),
      events: z.array(
        z.object({ id: z.string().nullable(), data: z.string() }),
      ),
    }),
  ),
});

const doc = Doc.parse(JSON.parse(readFileSync(FILE, "utf8")));

test("every table has rows, so an empty vector cannot pass quietly", () => {
  for (const rows of Object.values(doc)) expect(rows.length).toBeGreaterThan(0);
});

describe("vectors/a2a.json errors", () => {
  test("the table names every error we answer with", () => {
    expect(doc.errors.map((row) => row.name).toSorted()).toEqual(
      [...A2A_ERROR_NAMES].toSorted(),
    );
  });
  for (const row of doc.errors)
    test(row.name, () => {
      const name = A2A_ERROR_NAMES.find((known) => known === row.name);
      if (name === undefined)
        throw new Error(`${row.name} is not an A2A error`);
      expect<{ readonly code: number; readonly status: number }>(
        A2A_ERRORS[name],
      ).toEqual({ code: row.code, status: row.status });
    });
});

describe("vectors/a2a.json task_states", () => {
  for (const row of doc.task_states)
    test(row.name, () => {
      const parsed = TaskState.safeParse(row.state);
      expect(parsed.success).toBe(row.accepted);
      if (!parsed.success) return;
      const { terminal, interrupted } = row;
      if (terminal === undefined || interrupted === undefined)
        throw new Error(`${row.name}: an accepted state must pin both flags`);
      expect(isTerminal(parsed.data)).toBe(terminal);
      expect(isInterrupted(parsed.data)).toBe(interrupted);
    });
});

describe("vectors/a2a.json versions", () => {
  for (const row of doc.versions)
    test(row.name, () => {
      expect(checkVersion(row.header, row.query) === undefined).toBe(
        row.accepted,
      );
    });
});

describe("vectors/a2a.json paths", () => {
  for (const row of doc.paths)
    test(row.name, () => {
      const found = inboundPath(row.path);
      expect<string | null>(found?.method ?? null).toBe(row.method);
      expect<string | null>(found?.id ?? null).toBe(row.id);
    });
});

/** The raw body as a stream, in one chunk or a byte at a time. */
function bodyOf(raw: string, perByte: boolean): ReadableStream<Uint8Array> {
  const bytes = new TextEncoder().encode(raw);
  const chunks = perByte ? [...bytes].map((b) => Uint8Array.of(b)) : [bytes];
  return new ReadableStream<Uint8Array>({
    start(controller) {
      for (const chunk of chunks) controller.enqueue(chunk);
      controller.close();
    },
  });
}

async function eventsOf(
  raw: string,
  perByte: boolean,
): Promise<readonly { readonly id: string | null; readonly data: string }[]> {
  const out: { id: string | null; data: string }[] = [];
  for await (const event of sseEvents(bodyOf(raw, perByte)))
    out.push({ id: event.id ?? null, data: event.data });
  return out;
}

describe("vectors/a2a.json sse", () => {
  for (const row of doc.sse)
    test(row.name, async () => {
      expect(await eventsOf(row.raw, false)).toEqual(row.events);
      // A trailing "\r" may be the first half of a "\r\n", which only split chunks can show.
      expect(await eventsOf(row.raw, true)).toEqual(row.events);
    });
});
