"""The spec/otel goldens (generated by spec/tools/fixtures/otel.py), read as data."""

import json
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from threads.otel.otlp import body
from threads.otel.span import Span
from threads.otel.spans import Branch, spans
from threads.result import Ok
from threads.store.verify import VerifiedLog, verify_export

OTEL = Path(__file__).resolve().parents[2] / "spec" / "otel"
NOW = 1_790_000_060_000


class SyncPlan(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)
    branch_id: str
    head_seq: int
    cursor_before: int
    cursor_after: int
    spans: int
    expected: str | None = None


class CaseFile(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)
    name: str
    description: str
    tenant: str
    content: bool
    resource: dict[str, str]
    scope_version: str
    branches: list[str]
    syncs: list[SyncPlan]


@dataclass(frozen=True)
class Golden:
    case: CaseFile
    dir: Path
    logs: dict[str, VerifiedLog]


def goldens() -> list[Golden]:
    out: list[Golden] = []
    for d in sorted((OTEL / "cases").iterdir()):
        case = CaseFile.model_validate_json((d / "case.json").read_bytes())
        logs: dict[str, VerifiedLog] = {}
        for b in case.branches:
            log = verify_export((d / f"{b}.jsonl").read_bytes(), NOW)
            assert isinstance(log, Ok), f"{d.name}/{b}: {log}"
            logs[b] = log.value
        out.append(Golden(case, d, logs))
    return out


def synced(g: Golden, branch_id: str, cursor: int, head: int) -> tuple[Span, ...]:
    """The spans one sync of a golden sends: those closing in (cursor, head]."""
    branch = Branch(g.case.tenant, branch_id, g.logs[branch_id], g.case.content, through=head)
    return tuple(s for s in spans(branch, g.logs.get) if cursor < s.close_seq <= head)


def encode(g: Golden, sent: tuple[Span, ...]) -> bytes | None:
    return body(sent, g.case.resource, g.case.scope_version) if sent else None


def expected(g: Golden, file: str | None) -> bytes | None:
    return None if file is None else (g.dir / file).read_bytes()


def read_json(name: str) -> object:
    loaded: object = json.loads((OTEL / "vectors" / name).read_text())
    return loaded
